package com.przemyslawjakubowski.textOutput;

public enum OutputOption {
    STARTING,
    FIRST_PLAYER_NAME_QUESTION,
    SECOND_PLAYER_NAME_QUESTION,
    STARTING_PLAYER_QUESTION,
    EMPTY_PLAYER_NAME,
    WIDTH_QUESTION,
    LENGTH_QUESTION,
    SYMBOLS_AMOUNT_QUESTION,
    INCORRECT_VALUE,
    CURRENTLY_PLAYING,
    PLAYER_SCORE,
    CONGRATULATION,
    WON,
    ROUND_WON,
    TIE,
    EXCEPTION_BOARD_INDEX_OUT_OF_BOUND,
    EXCEPTION_FIELD_NOT_EMPTY,
    EXCEPTION_INCORRECT_SYMBOL,
    EXCEPTION_INCORRECT_COORDINATE,
    EXCEPTION_INCORRECT_AMOUNT_OF_SYMBOLS_TO_WIN,
    EXCEPTION_INCORRECT_POINTS_FOR_TIE,
    EXCEPTION_INCORRECT_POINTS_FOR_WON,
    EXCEPTION_BOARD_DIMENSION
}
